[package]
name = "package-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "libpm"
path = "src/libpm/lib.rs"

[[bin]]
name = "pm"
path = "src/bin/pm.rs"

[dependencies]
